### ISSUE TITLE
Rinex nav codesL2 , double vs short

### ISSUE THREAD

**Issue by jonyrock** [jonyrock/Gpstk#9]
see ftp://igscb.jpl.nasa.gov/pub/data/format/rinex211.txt table a4
and this https://github.com/jonyrock/Gpstk/blob/38f355122a8012f02eec9cf62d376b4e04294869/dev/ext/lib/FileHandling/RINEX3/Rinex3NavData.hpp#L170

So in gpstk we use short to store double. 

@eugenyk what do you think ?

**Comment by jonyrock** [comment]
@eugenyk same thing with `L2Pdata`

**Comment by jonyrock** [comment]
It is our fault actually.

**Comment by eugenyk** [comment]
@jonyrock According to the standard and http://stcorp.nl/coda/doc/codadef/codadef-rinex.html - they are double. I think http://binex.unavco.org/binex_record_01.html can give us understanding of values thresholds and RtkLib https://github.com/tomojitakasu/RTKLIB/blob/master/src/rtklib.h tells us that they are int, not short
